spring:
  application:
    name: r2dbc-demo


  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false

# R2DBC URL
r2dbc.url: r2dbc:h2:mem://./testdb

logging:
  level:
    nu.westlin.r2dbcdemo: debug
    root: info

